services:
  - type: web
    name: itrc-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node seed.js && node index.js
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: JWT_SECRET
        generateValue: true
